INSERT {
  ?sub <http://epa.gov/nrmrl/std/lca/ethold#hasInconsistency> _:b0 .
  _:b0 <http://epa.gov/nrmrl/std/lca/ethold#propertyInQuestion> <http://ontology.earthster.org/eco/core#casNumber> .
  _:b0 <http://www.w3.org/2000/01/rdf-schema#comment> "Failed regex: ^\\d{2,7}-\\d\\d-\\d$" .
}
WHERE
  { ?sub <http://ontology.earthster.org/eco/core#casNumber> ?cas
    FILTER ( ! regex(?cas, "^\\d{2,7}-\\d\\d-\\d$") )
#    ?sub <http://ontology.earthster.org/eco/core#hasDataSource> ?ds .
#    ?sub <http://www.w3.org/2000/01/rdf-schema#label> ?label .
#    ?sub <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://ontology.earthster.org/eco/core#Substance>
  }
