PREFIX  afn:  <http://jena.hpl.hp.com/ARQ/function#>
PREFIX  gc:   <http://data.actor.epa.gov/2012_q1/genericChemical#>
PREFIX  traci: <http://data.lca.std.nrmrl.epa.gov/harm_tool/TRACI2.1#>
PREFIX  xml:  <http://www.w3.org/XML/1998/namespace>
PREFIX  rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  ethold: <http://epa.gov/nrmrl/std/lca#>
PREFIX  owl:  <htp://www.w3.org/2002/07/owl#>
PREFIX  xsd:  <http://www.w3.org/2001/XMLSchema#>
PREFIX  rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  acto: <http://ontology.actor.epa.gov/core#>
PREFIX  fn:   <http://www.w3.org/2005/xpath-functions#>
PREFIX  eco:  <http://ontology.earthster.org/eco/core#>


SELECT ?source (count(?s) as ?count) WHERE
{{?s eco:hasDataSource ?source .} union
{?source a eco:DataSource .}
}
group by ?source

