prefix eco:    <http://ontology.earthster.org/eco/core#>
prefix ds_001: <http://epa.gov/nrmrl/std/lca/ethold/ds_001#>
prefix rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
prefix rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
prefix afn:    <http://jena.hpl.hp.com/ARQ/function#>

select ?flow ?o  where {
?s eco:hasImpactAssessmentMethodCateogryDescription ?o .
?s eco:hasFlowable ?flow .
#filter regex(str(?o),"impact")  
#filter (afn:namespace(?s) = "http://epa.gov/nrmrl/std/lca/ethold/ds_001#" )

#?s rdfs:label ?name .
#optional {?s eco:casNumber ?cas .}
}
