PREFIX  eco:    <http://ontology.earthster.org/eco/core#>
PREFIX  ethold: <http://epa.gov/nrmrl/std/lca/ethold#>
PREFIX  afn:    <http://jena.hpl.hp.com/ARQ/function#>
PREFIX  fn:     <http://www.w3.org/2005/xpath-functions#>
PREFIX  owl:    <http://www.w3.org/2002/07/owl#>
PREFIX  skos:   <http://www.w3.org/2004/02/skos/core#>
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX  rdfs:   <http://www.w3.org/2000/01/rdf-schema#>
PREFIX  xml:    <http://www.w3.org/XML/1998/namespace>
PREFIX  xsd:    <http://www.w3.org/2001/XMLSchema#>

SELECT (afn:localname(?s) as ?sourceIRI) (str(?label) as ?name) (concat(str(?mj),".",str(?mi)) as ?version) (str(?com) as ?comment) (str(count(?sub)) as ?Substances)
WHERE 
  { 
    ?s a eco:DataSource . 
    ?sub eco:hasDataSource ?s . 
    ?sub a eco:Substance . 
    OPTIONAL {?s rdfs:label ?label} 
    OPTIONAL {?s rdfs:comment ?com} 
    OPTIONAL { ?s eco:hasMajorVersionNumber ?mj } 
    OPTIONAL { ?s eco:hasMinorVersionNumber ?mi } 
}
group by ?s ?label ?mj ?mi ?com 
