#
PREFIX  eco:    <http://ontology.earthster.org/eco/core#> 
PREFIX  fedlca: <http://epa.gov/nrmrl/std/lca/fedlca/1.0#> 
PREFIX  lcaht: <http://epa.gov/nrmrl/std/lca/ht/1.0#> 
PREFIX  afn:    <http://jena.hpl.hp.com/ARQ/function#> 
PREFIX  fn:     <http://www.w3.org/2005/xpath-functions#> 
PREFIX  owl:    <http://www.w3.org/2002/07/owl#> 
PREFIX  skos:   <http://www.w3.org/2004/02/skos/core#> 
PREFIX  rdf:    <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX  rdfs:   <http://www.w3.org/2000/01/rdf-schema#> 
PREFIX  xml:    <http://www.w3.org/XML/1998/namespace> 
PREFIX  xsd:    <http://www.w3.org/2001/XMLSchema#> 
PREFIX  dcterms: <http://purl.org/dc/terms/>
PREFIX  dsstox:  <http://www.epa.gov/ncct/dsstox/ontology_01#>

select ?name ?cas ?ds_name
where {
dsstox:deletedCas eco:casNumber ?cas .
?sub eco:casNumber ?cas .
{?sub a eco:Substance .} UNION
{?sub a eco:Flowable .}
?sub rdfs:label ?name .
?sub eco:hasDataSource ?data_source .
?data_source rdfs:label ?ds_name .
}

